version: '3.9'

services:
  mysql:
    image: mysql:8.0.30
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - mysqld-data:/var/run/mysqld

  phpmyadmin:
    image: phpmyadmin:5.2.0-fpm-alpine
    restart: always
    expose:
      - 9000
    environment:
      PMA_HOST: mysql
      PMA_ABSOLUTE_URI: https://*/phpmyadmin/
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - phpmyadmin-data:/var/www/html/

  web:
    build: .
    command: gunicorn esufrn.wsgi:application --bind 0.0.0.0:8000
    restart: always
    expose:
      - 8000
    depends_on:
      - mysql
    volumes:
      - mysqld-data:/run/mysqld
    env_file:
      - ./.env

  nginx:
    build:
      context: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
      - phpmyadmin
    volumes:
      - ./src/public:/usr/share/nginx/html
      - phpmyadmin-data:/var/www/html/
      - ./nginx/ssl:/ssl

volumes:
  mysqld-data:
  mysql-data:
  phpmyadmin-data:
