version: "3.9"

services:
    mysql:
        image: mysql:8.0.30
        restart: always
        expose:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_ROOT_HOST: "localhost"
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - mysql-data:/var/lib/mysql
            - mysqld-data:/var/run/mysqld
            - ./mysql:/docker-entrypoint-initdb.d

    phpmyadmin:
        image: phpmyadmin:5.2.0-fpm-alpine
        restart: always
        expose:
            - 9000
        environment:
            PMA_HOST: mysql
            PMA_ABSOLUTE_URI: https://*/phpmyadmin/
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            UPLOAD_LIMIT: 32M
        depends_on:
            - mysql
        links:
            - mysql
        volumes:
            - phpmyadmin-data:/var/www/html

    redis:
        image: redis
        expose:
            - 6379
        volumes:
            - redis-data:/data

    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        restart: always
        expose:
            - 8000
        depends_on:
            - mysql
            - redis
        volumes:
            - mysqld-data:/run/mysqld
            - ./src:/usr/src/app/src

    nginx:
        build:
            context: nginx
        restart: always
        ports:
            - 80:80
            - 443:443
        depends_on:
            - web
            - phpmyadmin
        volumes:
            - phpmyadmin-data:/var/www/html/phpmyadmin:ro
            - ./src/staticfiles:/usr/share/nginx/html/staticfiles:ro
            - ./src/media:/usr/share/nginx/html/media:ro
            - ./src/templates:/usr/share/nginx/html/templates:ro
            - ./nginx/ssl:/ssl:ro

volumes:
    mysqld-data:
    mysql-data:
    phpmyadmin-data:
    redis-data:
