version: "3.9"

services:
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data

    redis:
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data



volumes:
    postgres-data:
    redis-data:
