version: '3.9'

services:
  mysql:
    image: mysql:8.0.30
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "localhost"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - mysqld-data:/var/run/mysqld
      - ./mysql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin:5.2.0-fpm-alpine
    restart: always
    expose:
      - 9000
    environment:
      PMA_HOST: mysql
      PMA_ABSOLUTE_URI: https://*/phpmyadmin/
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - phpmyadmin-data:/var/www/html/

  web:
    build: .
    command: gunicorn esufrn.wsgi:application --workers 4 --threads 2 --bind 0.0.0.0:8000
    restart: always
    expose:
      - 8000
    depends_on:
      - mysql
    volumes:
      - mysqld-data:/run/mysqld
      - ./public:/vol/web
    env_file:
      - ./.env

  planeja:
    build:
      context: ./planeja
      dockerfile: Dockerfile
    expose:
      - 9000
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - ./planeja:/var/www/html/

  nginx:
    build:
      context: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
      - phpmyadmin
    links:
      - planeja
    volumes:
      - ./public:/usr/share/nginx/html
      - ./nginx/ssl:/ssl
      - phpmyadmin-data:/var/www/html/phpmyadmin/
      - ./planeja:/var/www/html/planeja/

volumes:
  mysqld-data:
  mysql-data:
  phpmyadmin-data:
