# Generated by Django 4.0.8 on 2022-11-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubSubItens',
        ),
    ]
