# Generated by Django 4.0.8 on 2022-11-30 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_delete_subsubitens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subitens',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subitems', to='menu.itens'),
        ),
    ]
