# Generated by Django 4.0.8 on 2022-11-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_subitens_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subitens',
            name='action_type',
        ),
    ]
