# Generated by Django 4.1 on 2022-09-01 21:55

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Conteúdo')),
                ('expires_at', models.DateTimeField(verbose_name='Exibir até')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Arquivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
                ('file', models.FileField(max_length=255, null=True, upload_to='files/', verbose_name='Arquivo')),
                ('published_at', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Adicionado em')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Título da notícia')),
                ('subtitle', models.CharField(max_length=500, verbose_name='Subtítulo da notícia')),
                ('slug', models.SlugField(help_text='Este campo será preenchido automaticamente, ele representa a URL da notícia. Ele é único e nenhuma outra notícia deverá ter o mesmo atalho.', max_length=255, verbose_name='Atalho')),
                ('news', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Notícia')),
                ('isImportant', models.BooleanField(default=False, help_text='Caso seja marcado, esse campo indica a notícia aparecerá no slide da página principal, logo abaixo do menu.', verbose_name='Destaque?')),
                ('author', models.CharField(max_length=50, verbose_name='Nome do autor')),
                ('category', models.CharField(choices=[('noticia', 'Notícia (Newsletter - Notícias)'), ('evento', 'Evento'), ('processo', 'Processo (Newsletter - Abertura de Turmas)'), ('concurso', 'Concurso (Newsletter - Editais de Cursos)')], default='notícia', max_length=8, verbose_name='Categoria')),
                ('image', models.ImageField(blank=True, help_text='Esta imagem será a capa da postagem. Ela aparecerá no topo da página da notícia, no plano de fundo do link na página principal e no plano de fundo do link no Facebook.', null=True, upload_to='blog/imagens', verbose_name='Imagem da postagem')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Publicado em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='Depoimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('occupation', models.CharField(max_length=100, verbose_name='Ocupação')),
                ('testimonial', models.CharField(max_length=100, verbose_name='Depoimento')),
                ('file', models.FileField(blank=True, null=True, upload_to='depoimentos/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
                ('authors', models.CharField(blank=True, help_text="Nome autor ou dos autores, separados por ';'", max_length=250, null=True, verbose_name='Autores')),
                ('category', models.CharField(choices=[('institucional', 'Institucional'), ('ensino', 'Ensino'), ('outros', 'Outros documentos'), ('publicacoes', 'Publicações')], max_length=32, verbose_name='Categoria')),
                ('document_type', models.CharField(choices=[('arquivo', 'Arquivo'), ('link', 'Link')], default='arquivo', help_text='Documento: Ao clicar, abrirá o documento em uma nova guia; Link: Ao clicar abrirá o link inserido em uma nova guia.', max_length=100, verbose_name='Tipo')),
                ('file', models.FileField(blank=True, max_length=255, upload_to='files/documentos', verbose_name='Arquivo')),
                ('link', models.CharField(blank=True, max_length=1024, verbose_name='Link')),
                ('date', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data do documento')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Publicado em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-date', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('photo', models.ImageField(default='/equipe/base/avatar.jpg', upload_to='equipe/imagens', verbose_name='Imagem da Servidor')),
                ('kind', models.CharField(choices=[('docente', 'Docente'), ('servidor', 'Servidor')], default='docente', max_length=8, verbose_name='Tipo')),
                ('sigaa', models.URLField(blank=True, max_length=300)),
                ('cv', models.URLField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipe',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('contact', models.CharField(max_length=100, verbose_name='Contato')),
                ('message', models.CharField(max_length=500, verbose_name='Mensagem')),
                ('sent_at', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Enviado em')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_person', models.CharField(max_length=110, verbose_name='Nome')),
                ('email', models.EmailField(max_length=110, verbose_name='Email')),
                ('category', multiselectfield.db.fields.MultiSelectField(choices=[('editais', 'Editais de Cursos'), ('turmas', 'Abertura de Turmas'), ('outras', 'Outras Notícias')], max_length=21, verbose_name='Tipo')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Inscrito desde')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Última atualização')),
                ('consent', models.BooleanField(default=False, help_text='Ao marcar essa caixa, o usuário declara que leu e concorda com a política de privacidade da ESUFRN.', verbose_name='Termos de uso')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletter',
                'ordering': ['name_person'],
            },
        ),
        migrations.CreateModel(
            name='Paginas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Será o título da página', max_length=250, verbose_name='Nome')),
                ('path', models.SlugField(help_text="Insira todo o caminho (PATH) depois de 'escoladesaude.ufrn.br/pagina/'. Não insira novas '/'", max_length=250, unique=True, verbose_name='Caminho')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Conteúdo')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['path', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Publicacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Arquivo')),
                ('category', models.CharField(choices=[('pub', 'Publicação'), ('com', 'Comitê de Ética'), ('eno', 'Especialização em Enfermagem Obstétrica')], default='pub', max_length=3, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogAttachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.blog')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.arquivos', verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['blog__title'],
            },
        ),
    ]
