# Generated by Django 4.2.11 on 2025-02-03 18:24

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Conteúdo')),
                ('expires_at', models.DateTimeField(verbose_name='Exibir até')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Cursos_Pronatec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='cursos_pronatec/')),
                ('link', models.URLField()),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Cursos_PRONATEC',
                'ordering': ['ordem', 'nome_curso'],
            },
        ),
        migrations.CreateModel(
            name='destaque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Título', max_length=25)),
                ('tipo', models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo')], default='imagem', max_length=10)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='destaques/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Destaque_PRONATEC',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
                ('authors', models.CharField(blank=True, help_text="Nome autor ou dos autores, separados por ';'", max_length=250, null=True, verbose_name='Autores')),
                ('category', models.CharField(choices=[('institucional', 'Institucional'), ('ensino', 'Ensino'), ('outros', 'Outros documentos'), ('publicacoes', 'Publicações')], help_text='Caso selecione a categoria Ensino, escolha uma subcategoria.', max_length=32, verbose_name='Categoria')),
                ('document_type', models.CharField(choices=[('arquivo', 'Arquivo'), ('link', 'Link')], default='arquivo', help_text='Documento: Ao clicar, abrirá o documento em uma nova guia; Link: Ao clicar abrirá o link inserido em uma nova guia.', max_length=100, verbose_name='Tipo')),
                ('ensino_subcategory', models.CharField(blank=True, choices=[('cursos_tecnicos', 'Cursos Técnicos'), ('graduacao_tecnologica', 'Graduação Tecnológica')], max_length=32, null=True, verbose_name='Subcategoria de Ensino')),
                ('file', models.FileField(blank=True, max_length=255, upload_to='files/documentos', verbose_name='Arquivo')),
                ('link', models.CharField(blank=True, max_length=1024, verbose_name='Link')),
                ('date', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data do documento')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['is_active', '-date'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
                ('file', models.FileField(max_length=255, null=True, upload_to='files/', verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Links_V',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='imagens/')),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Videos_PRONATEC',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('contact', models.CharField(max_length=100, verbose_name='Contato')),
                ('message', models.CharField(max_length=500, verbose_name='Mensagem')),
                ('sent_at', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Enviado em')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=400, verbose_name='Título da notícia')),
                ('subtitle', models.CharField(max_length=500, verbose_name='Subtítulo da notícia')),
                ('slug', models.SlugField(help_text='Este campo será preenchido automaticamente, ele representa a URL da notícia. Ele é único e nenhuma outra notícia deverá ter o mesmo atalho.', max_length=255, verbose_name='Atalho')),
                ('news', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Notícia')),
                ('is_important', models.BooleanField(default=True, help_text='Caso seja marcado, esse campo indica a notícia aparecerá no carrossel da página principal, logo abaixo do menu.', verbose_name='Destaque?')),
                ('published', models.BooleanField(default=True, help_text='Com esta opção marcada, a publicação ficará disponível no site imediatamente.', verbose_name='Publicada')),
                ('published_at', models.DateTimeField(null=True)),
                ('publish_in', models.DateTimeField(blank=True, help_text='Você pode agendar uma data para que seja feita a publicação.', null=True, verbose_name='Publicar em')),
                ('author', models.CharField(max_length=50, verbose_name='Nome do autor')),
                ('category', models.CharField(choices=[('noticia', 'Notícia (Newsletter - Notícias)'), ('evento', 'Evento'), ('processo', 'Processo (Newsletter - Abertura de Turmas)'), ('concurso', 'Concurso (Newsletter - Editais de Cursos)')], default='noticia', max_length=8, verbose_name='Categoria')),
                ('image', models.ImageField(blank=True, help_text='Esta imagem será a capa da postagem. Ela aparecerá no topo da página da notícia, no plano de fundo do link na página principal e no plano de fundo do link no Facebook.', null=True, upload_to='blog/imagens', verbose_name='Imagem da postagem')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_person', models.CharField(max_length=110, verbose_name='Nome')),
                ('email', models.EmailField(max_length=110, verbose_name='Email')),
                ('category', multiselectfield.db.fields.MultiSelectField(choices=[('editais', 'Editais de Cursos'), ('turmas', 'Abertura de Turmas'), ('outras', 'Outras Notícias')], max_length=21, verbose_name='Tipo')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Inscrito desde')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Última atualização')),
                ('consent', models.BooleanField(default=False, help_text='Ao marcar essa caixa, o usuário declara que leu e concorda com a política de privacidade da ESUFRN.', verbose_name='Termos de uso')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletter',
                'ordering': ['name_person'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=400)),
                ('link', models.URLField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Noticias_PRONATEC',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Será o título da página', max_length=250, verbose_name='Nome')),
                ('path', models.SlugField(help_text="Insira todo o caminho (PATH) depois de 'escoladesaude.ufrn.br/pagina/'. Não insira novas '/'", max_length=250, unique=True, verbose_name='Caminho')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Conteúdo')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['path', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('descricao', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Fotos_PRONATEC',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('photo', models.ImageField(default='/equipe/base/avatar.jpg', upload_to='equipe/imagens', verbose_name='Imagem da Servidor')),
                ('kind', models.CharField(choices=[('docente', 'Docente'), ('servidor', 'Servidor')], default='docente', max_length=8, verbose_name='Tipo')),
                ('sigaa', models.URLField(blank=True, max_length=300)),
                ('cv', models.URLField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipe',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('occupation', models.CharField(max_length=100, verbose_name='Ocupação')),
                ('testimonial', models.CharField(max_length=100, verbose_name='Depoimento')),
                ('file', models.FileField(blank=True, null=True, upload_to='depoimentos/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='principal.news')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.file', verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['blog__title'],
            },
        ),
    ]
