# Generated by Django 4.2.11 on 2025-05-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('site', 'Acesso geral ao site'), ('noticia', 'Visualização de notícia'), ('processo', 'Visualização de processo seletivo')], max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID da notícia ou processo, se aplicável', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
