# Generated by Django 4.0.7 on 2022-10-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_revista'),
    ]

    operations = [
        migrations.AddField(
            model_name='revista',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='revistas/', verbose_name='Arquivo'),
        ),
        migrations.AddField(
            model_name='revista',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='revista',
            name='image',
            field=models.ImageField(upload_to='revistas/capas', verbose_name='Capa da revista'),
        ),
        migrations.AlterField(
            model_name='revista',
            name='type',
            field=models.CharField(choices=[('LNK', 'Link'), ('DOC', 'Documento')], max_length=4, verbose_name='Tipo'),
        ),
    ]
