# Generated by Django 4.2.20 on 2026-03-25 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("principal", "0002_pageview_news_views"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cursos_Formatec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_curso", models.CharField(max_length=100)),
                ("imagem", models.ImageField(upload_to="cursos_formatec/")),
                ("link", models.URLField()),
                ("ordem", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Cursos_FORMATEC",
                "ordering": ["ordem", "nome_curso"],
            },
        ),
        migrations.CreateModel(
            name="Destaque_Formatec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(default="Título", max_length=25)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("imagem", "Imagem"), ("video", "Vídeo")],
                        default="imagem",
                        max_length=10,
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        blank=True, null=True, upload_to="destaques_formatec/"
                    ),
                ),
                (
                    "video_file",
                    models.FileField(blank=True, null=True, upload_to="videos_formatec/"),
                ),
                ("link", models.URLField()),
            ],
            options={
                "verbose_name_plural": "Destaque_FORMATEC",
            },
        ),
        migrations.CreateModel(
            name="Links_V_Formatec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("imagem", models.ImageField(upload_to="imagens_formatec/")),
                ("link", models.URLField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "Videos_FORMATEC",
            },
        ),
        migrations.CreateModel(
            name="Noticia_Formatec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=400)),
                ("link", models.URLField()),
                (
                    "data_criacao",
                    models.DateTimeField(auto_now_add=True, blank=True, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Noticias_FORMATEC",
            },
        ),
        migrations.CreateModel(
            name="Photo_Formatec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="photos_formatec/")),
                ("descricao", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name_plural": "Fotos_FORMATEC",
                "ordering": ["-date_created"],
            },
        ),
    ]
