# Generated by Django 4.0.8 on 2022-11-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_blog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('noticia', 'Notícia (Newsletter - Notícias)'), ('evento', 'Evento'), ('processo', 'Processo (Newsletter - Abertura de Turmas)'), ('concurso', 'Concurso (Newsletter - Editais de Cursos)')], default='noticia', max_length=8, verbose_name='Categoria'),
        ),
    ]
