# Generated by Django 3.2.8 on 2023-11-06 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='caption',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='caption',
            new_name='descricao',
        ),
    ]
