# Generated by Django 3.2.8 on 2023-11-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_auto_20231106_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destaque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('video', 'Vídeo')], max_length=10)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='destaques/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('link', models.URLField()),
            ],
        ),
    ]
