# Generated by Django 4.0.8 on 2022-11-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_alter_blog_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='News',
        ),
    ]
