# Generated by Django 3.2.8 on 2023-11-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_destaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='destaque',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
