# Generated by Django 4.0.8 on 2022-11-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_rename_blog_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipe',
            new_name='Team',
        ),
    ]
