# Generated by Django 4.0.8 on 2022-11-30 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_rename_equipe_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Arquivos',
            new_name='File',
        ),
        migrations.DeleteModel(
            name='Publicacoes',
        ),
    ]
