# Generated by Django 3.2.8 on 2023-11-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_auto_20231108_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destaque',
            name='titulo',
            field=models.CharField(default='Título', max_length=25),
        ),
    ]
