# Generated by Django 4.0.8 on 2022-11-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_rename_arquivos_file_delete_publicacoes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogAttachments',
            new_name='NewsAttachment',
        ),
    ]
