# Generated by Django 3.2.8 on 2023-11-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_alter_destaque_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='destaque',
            name='tipo',
            field=models.CharField(choices=[('video', 'Vídeo'), ('imagem', 'Imagem')], default='imagem', max_length=10),
        ),
    ]
