# Generated by Django 4.0.8 on 2022-11-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_rename_paginas_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Depoimentos',
            new_name='Testimonial',
        ),
    ]
