# Generated by Django 3.2.8 on 2023-11-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_destaque_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destaque',
            name='tipo',
            field=models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo')], default='imagem', max_length=10),
        ),
    ]
