# Generated by Django 4.0.8 on 2022-11-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_rename_depoimentos_testimonial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documentos',
            new_name='Document',
        ),
    ]
