# Generated by Django 3.2.8 on 2023-12-04 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_noticia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'verbose_name_plural': 'Noticias_PRONATEC'},
        ),
    ]
