# Generated by Django 4.0.8 on 2022-11-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_rename_documentos_document'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mensagem',
            new_name='Message',
        ),
    ]
