# Generated by Django 3.2.8 on 2023-12-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_alter_noticia_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links_V',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='imagens/')),
                ('link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
