# Generated by Django 4.0.8 on 2022-11-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_rename_mensagem_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alerta',
            new_name='Alert',
        ),
    ]
