# Generated by Django 4.0.8 on 2022-11-30 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_rename_alerta_alert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created'], 'verbose_name': 'Alerta', 'verbose_name_plural': 'Alertas'},
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='modified_at',
            new_name='modified',
        ),
    ]
