# Generated by Django 3.2.8 on 2023-12-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_auto_20231205_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='links_v',
            options={'verbose_name_plural': 'Videos_pronatec'},
        ),
    ]
