# Generated by Django 3.2.8 on 2023-12-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_alter_links_v_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos_Pronatec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='cursos_pronatec/')),
                ('link', models.URLField()),
                ('descricao', models.TextField()),
            ],
        ),
    ]
