# Generated by Django 4.0.8 on 2022-11-30 17:18

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_alter_alert_options_rename_created_at_alert_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
