# Generated by Django 3.2.8 on 2023-12-15 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_cursos_pronatec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos_pronatec',
            name='descricao',
        ),
    ]
