# Generated by Django 4.0.9 on 2023-02-14 00:42

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("principal", "0015_alter_alert_created_alter_alert_modified"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["is_active", "-date"],
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
            },
        ),
        migrations.RenameField(
            model_name="document",
            old_name="modified_at",
            new_name="modified",
        ),
        migrations.RenameField(
            model_name="document",
            old_name="published_at",
            new_name="created",
        ),
        migrations.AddField(
            model_name="document",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
