# Generated by Django 3.2.8 on 2023-12-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0016_remove_cursos_pronatec_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos_pronatec',
            options={'verbose_name_plural': 'Cursos_PRONATEC'},
        ),
    ]
