# Generated by Django 4.0.9 on 2023-02-17 01:20

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("principal", "0017_alter_document_created_alter_document_modified"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="published_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="news",
            old_name="modified_at",
            new_name="modified",
        ),
        migrations.AddField(
            model_name="file",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="publish_in",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "Você pode agendar uma data para que seja feita a publicação."
                ),
                null=True,
                verbose_name="Publicar em",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="published",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="isImportant",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Caso seja marcado, esse campo indica a notícia aparecerá no"
                    " carrossel da página principal, logo abaixo do menu."
                ),
                verbose_name="Destaque?",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="published_at",
            field=models.DateTimeField(null=True),
        ),
    ]
