# Generated by Django 3.2.8 on 2023-12-18 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0018_auto_20231218_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name_plural': 'Fotos_PRONATEC'},
        ),
    ]
