# Generated by Django 4.0.9 on 2023-02-17 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0018_remove_file_published_at_remove_news_modified_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='isImportant',
            new_name='is_important',
        ),
    ]
