# Generated by Django 3.2.8 on 2024-01-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0019_alter_photo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=400),
        ),
    ]
