# Generated by Django 4.0.9 on 2023-02-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0020_alter_file_created_alter_news_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='is_important',
            field=models.BooleanField(default=True, help_text='Caso seja marcado, esse campo indica a notícia aparecerá no carrossel da página principal, logo abaixo do menu.', verbose_name='Destaque?'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.BooleanField(default=True, help_text='Com esta opção marcada, a publicação ficará disponível no site imediatamente.', verbose_name='Publicada'),
        ),
    ]
