# Generated by Django 3.2.8 on 2024-01-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0022_alter_cursos_pronatec_nome_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
