# Generated by Django 3.2.8 on 2024-01-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0023_noticia_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos_pronatec',
            name='nome_curso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=400),
        ),
    ]
