# Generated by Django 4.0.9 on 2023-09-22 19:36

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(max_length=300, verbose_name='Descrição do problema')),
                ('requester', models.CharField(max_length=50, verbose_name='Nome completo')),
                ('course', models.CharField(max_length=100, verbose_name='Nome do curso')),
                ('contact', models.CharField(max_length=50, verbose_name='Whatsapp ou Email para contato')),
                ('presence', models.BooleanField(default=False, help_text='Marcando esta caixa, você declara que a sala contará com a supervisão de um docente no momento da aula.', verbose_name='Supervisionado por docente')),
                ('date1', models.DateField(verbose_name='Data *')),
                ('shift', models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde')], default='M', max_length=1, verbose_name='Turno *')),
                ('solved_at', models.DateTimeField(null=True, verbose_name='Resolvido em')),
                ('obs', models.TextField(null=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('R', 'Resolvido'), ('N', 'Não resolvido'), ('P', 'Pendente')], default='P', max_length=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'ordering': ['-created'],
            },
        ),
    ]
