# Generated by Django 4.0.9 on 2023-09-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='presence',
            field=models.BooleanField(help_text='Marcando esta caixa, você declara que a sala contará com a supervisão de um docente no momento da aula.', null=True, verbose_name='Supervisionado por docente'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='shift',
            field=models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde')], max_length=1, null=True, verbose_name='Turno *'),
        ),
    ]
