# Generated by Django 4.0.7 on 2022-10-15 22:59

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='lastModified',
        ),
        migrations.AddField(
            model_name='chamado',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chamado',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='contact',
            field=models.CharField(max_length=50, verbose_name='Whatsapp ou Email'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='obs',
            field=models.TextField(null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='solved_at',
            field=models.DateTimeField(null=True, verbose_name='Resolvido em'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('Resolved', 'Resolved'), ('Not resolved', 'Not Resolved'), ('Pending', 'Pending')], default='Pending', max_length=12, verbose_name='Status'),
        ),
    ]
