# Generated by Django 4.0.9 on 2023-10-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0002_alter_chamado_presence_alter_chamado_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='presence',
        ),
        migrations.AddField(
            model_name='chamado',
            name='presenca',
            field=models.BooleanField(help_text='Marcando esta caixa, você declara que a sala contará com a supervisão de um docente no momento da aula.', null=True, verbose_name='Supervisionado por docente'),
        ),
    ]
