# Generated by Django 4.0.7 on 2022-10-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0002_remove_chamado_lastmodified_chamado_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamado',
            options={'ordering': ['-created'], 'verbose_name': 'Chamado', 'verbose_name_plural': 'Chamados'},
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='date',
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('R', 'Resolved'), ('N', 'Not resolved'), ('P', 'Pending')], default='P', max_length=1, verbose_name='Status'),
        ),
    ]