# Generated by Django 4.0.9 on 2023-02-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0003_alter_chamado_options_remove_chamado_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('R', 'Resolvido'), ('N', 'Não resolvido'), ('P', 'Pendente')], default='P', max_length=1, verbose_name='Status'),
        ),
    ]