# Generated by Django 4.0.9 on 2023-10-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0004_remove_chamado_presenca_chamado_presence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='presence',
        ),
        migrations.AddField(
            model_name='chamado',
            name='presenca',
            field=models.BooleanField(default=True, help_text='Marcando esta caixa, você declara que a sala contará com a supervisão de um docente no momento da aula.', verbose_name='Supervisionado por docente'),
            preserve_default=False,
        ),
    ]
