# Generated by Django 4.0.9 on 2023-10-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0006_alter_chamado_presenca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='presenca',
        ),
        migrations.AddField(
            model_name='chamado',
            name='concorda',
            field=models.CharField(choices=[('y', 'SIM')], default='Y', max_length=1, verbose_name='Marcando esta caixa você declara que estará presente no momento da manutenção'),
            preserve_default=False,
        ),
    ]
