# Generated by Django 5.0.7 on 2026-05-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0007_sala_and_chamado_room_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
