# Generated by Django 4.0.9 on 2023-09-18 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Nome da sala')),
                ('acronym', models.CharField(blank=True, max_length=16, null=True, verbose_name='Acrônimo')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='Capacidade')),
                ('type', models.CharField(choices=[('sal', 'Sala de aula'), ('lab', 'Laboratório'), ('aud', 'Auditório')], max_length=3, verbose_name='Tipo de sala')),
                ('number', models.CharField(max_length=10, verbose_name='Número da sala')),
                ('public', models.BooleanField(default=True, verbose_name='Visível ao público')),
                ('days_required', models.IntegerField(default=1, verbose_name='Prazo mínimo de reserva')),
                ('justification_required', models.BooleanField(default=False, verbose_name='Requer justificativa de uso')),
                ('floor', models.CharField(choices=[('0', 'Térreo'), ('1', '1º Andar')], default='0', max_length=25, verbose_name='Andar')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['floor', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('E', 'Esperando'), ('C', 'Cancelada'), ('R', 'Rejeitada'), ('A', 'Aprovada'), ('D', 'Concluída')], default='E', max_length=1, verbose_name='Estado da reserva')),
                ('date_begin', models.DateField(verbose_name='Início do período')),
                ('date_end', models.DateField(verbose_name='Fim do período')),
                ('workload', models.IntegerField(null=True, verbose_name='Carga horária')),
                ('weekdays', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Segunda'), ('2', 'Terça'), ('3', 'Quarta'), ('4', 'Quinta'), ('5', 'Sexta'), ('6', 'Sábado'), ('7', 'Domingo')], max_length=13, verbose_name='Dias da semana')),
                ('classname', models.CharField(max_length=100, verbose_name='Nome da turma')),
                ('classcode', models.CharField(max_length=16, verbose_name='Código do componente')),
                ('course', models.CharField(choices=[('ESU01', 'Técnico em Enfermagem'), ('ESU02', 'Técnico em Registros e Informações em Saúde'), ('ESU06', 'Técnico em Vigilância em Saúde'), ('ESU05', 'Técnico em Agente Comunitário de Saúde'), ('ESU07', 'Técnico em Massoterapia'), ('ESU10', 'Graduação Tecnológica em Gestão Hospitalar'), ('MPPSE', 'Mestrado Profissional'), ('ENF', 'Outros')], max_length=8, verbose_name='Nome do curso')),
                ('period', models.CharField(max_length=8, verbose_name='Período letivo')),
                ('class_period', models.CharField(max_length=8, verbose_name='Turma')),
                ('shift', multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], max_length=5, verbose_name='Turno')),
                ('requester', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=16, verbose_name='Telefone')),
                ('equipment', models.CharField(blank=True, help_text='Informe se preciso, algum equipamento ou software adicional necessário para as aulas.', max_length=200, null=True, verbose_name='Equipamento multimídia')),
                ('obs', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Observação')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.classroom', verbose_name='Sala de aula')),
            ],
            options={
                'verbose_name': 'Reserva de período',
                'verbose_name_plural': 'Reservas de período',
                'ordering': ['-period', '-class_period', 'course', 'date_begin', 'date_end', 'classname'],
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('event', models.CharField(max_length=100, verbose_name='Evento')),
                ('requester', models.CharField(max_length=100, verbose_name='Nome do solicitante')),
                ('date', models.DateField(verbose_name='Data para a reserva')),
                ('shift', models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], max_length=1, verbose_name='Turno')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Telefone')),
                ('cause', models.TextField(blank=True, max_length=512, null=True, verbose_name='Justificativa')),
                ('equipment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Equipamento multimídia')),
                ('status', models.CharField(choices=[('E', 'Esperando'), ('C', 'Cancelada'), ('R', 'Rejeitada'), ('A', 'Aprovada'), ('D', 'Concluída')], default='E', max_length=1, verbose_name='Estado da reserva')),
                ('obs', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Observação')),
                ('email_response', models.TextField(blank=True, null=True, verbose_name='Resposta')),
                ('declare', models.BooleanField(default=False, help_text='Marcando esta caixa, você declara que a sala contará com a supervisão de um docente no momento da aula.', verbose_name='Supervisionado por docente')),
                ('admin_created', models.BooleanField(default=False, verbose_name='Criado pela administração')),
                ('uuid', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.classroom', verbose_name='Sala de aula')),
            ],
            options={
                'verbose_name': 'Reserva pontual',
                'verbose_name_plural': 'Reservas pontuais',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ReserveDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data da reserva')),
                ('shift', models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], max_length=1)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='reserva.classroom')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='reserva.period')),
                ('reserve', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='reserva.reserve')),
            ],
            options={
                'verbose_name': 'Dia da reserva',
                'verbose_name_plural': 'Dias da reserva',
                'ordering': ['date', 'shift'],
            },
        ),
        migrations.CreateModel(
            name='UserClassroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to='reserva.classroom', verbose_name='Sala')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
                'unique_together': {('user', 'classroom')},
            },
        ),
    ]
