# Generated by Django 4.1 on 2022-09-01 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Nome da sala')),
                ('acronym', models.CharField(blank=True, max_length=16, null=True, verbose_name='Acrônimo')),
                ('type', models.CharField(choices=[('sal', 'Sala de aula'), ('lab', 'Laboratório'), ('aud', 'Auditório')], max_length=3, verbose_name='Tipo de sala')),
                ('number', models.CharField(max_length=10, verbose_name='Número da sala')),
                ('days_required', models.IntegerField(default=1, verbose_name='Prazo mínimo de reserva')),
                ('justification_required', models.BooleanField(default=False, verbose_name='Requer justificativa de uso')),
                ('floor', models.CharField(choices=[('0', 'Térreo'), ('1', '1º Andar')], default='0', max_length=25, verbose_name='Andar')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['floor', 'number'],
            },
        ),
        migrations.CreateModel(
            name='MaterialReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodReserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Aprovado'), ('R', 'Rejeitado'), ('E', 'Esperando')], default='E', max_length=1, verbose_name='Estado da reserva')),
                ('date_begin', models.DateField(verbose_name='Início do período')),
                ('date_end', models.DateField(verbose_name='Fim do período')),
                ('workload', models.IntegerField(null=True, verbose_name='Carga horária')),
                ('weekdays', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=14, verbose_name='Dias da semana')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da reserva')),
                ('refresh_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização da reserva')),
                ('classname', models.CharField(max_length=100, verbose_name='Nome da turma')),
                ('classcode', models.CharField(max_length=16, null=True, verbose_name='Código do componente')),
                ('course', models.CharField(choices=[('ESU01', 'Técnico em Enfermagem'), ('ESU02', 'Técnico em Registros e Informações em Saúde'), ('ESU06', 'Técnico em Vigilância em Saúde'), ('ESU05', 'Técnico em Agente Comunitário de Saúde'), ('ESU07', 'Técnico em Massoterapia'), ('ESU10', 'Graduação Tecnológica em Gestão Hospitalar'), ('MPPSE', 'Mestrado Profissional'), ('ENF', 'Outros')], max_length=8, null=True, verbose_name='Nome do curso')),
                ('period', models.CharField(default='2022.2', max_length=8, verbose_name='Período letivo')),
                ('class_period', models.CharField(default='2021.2', help_text='Ano de ingresso. Ex: 2020.2, 2021.6', max_length=8, verbose_name='Turma')),
                ('shift', multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], max_length=6, verbose_name='Turno')),
                ('requester', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=16, verbose_name='Telefone')),
                ('equipment', models.CharField(blank=True, help_text='Informe se preciso, algum equipamento ou software adicional necessário para as aulas.', max_length=200, null=True, verbose_name='Equipamento multimídia')),
                ('obs', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Observação')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_reserves', to='reserva.classroom', verbose_name='Sala de aula')),
            ],
            options={
                'verbose_name': 'Reserva de período',
                'verbose_name_plural': 'Reservas de período',
                'ordering': ['-period', '-class_period', 'course', 'date_begin', 'date_end', 'classname'],
            },
        ),
        migrations.CreateModel(
            name='UserClassroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.classroom', verbose_name='Sala')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data para a reserva')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data do pedido')),
                ('refresh_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização do pedido')),
                ('event', models.CharField(max_length=100, null=True, verbose_name='Evento')),
                ('shift', models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], default='M', max_length=1, verbose_name='Turno')),
                ('cause', models.TextField(blank=True, max_length=512, null=True, verbose_name='Justificativa')),
                ('equipment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Equipamento multimídia')),
                ('requester', models.CharField(max_length=100, verbose_name='Nome do solicitante')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Telefone')),
                ('status', models.CharField(choices=[('A', 'Aprovado'), ('R', 'Rejeitado'), ('E', 'Esperando')], default='E', max_length=1, verbose_name='Estado da reserva')),
                ('obs', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Observação')),
                ('email_response', models.TextField(blank=True, null=True, verbose_name='Resposta')),
                ('declare', models.BooleanField(default=False, help_text='Marcando esta caixa, você declara que a sala contará com a supervisão de um docente no momento da aula.', verbose_name='Supervisionado por docente')),
                ('admin_created', models.BooleanField(default=False, verbose_name='Criado pela administração')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='reserva.classroom', verbose_name='Sala de aula')),
            ],
            options={
                'verbose_name': 'Reserva pontual',
                'verbose_name_plural': 'Reservas pontuais',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeriodReserveDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data da reserva')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('shift', models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], default='M', max_length=1, verbose_name='Turno')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.periodreserve', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Dia da reserva',
                'verbose_name_plural': 'Dias da reserva',
                'ordering': ['date', 'shift'],
            },
        ),
    ]
