# Generated by Django 4.0.8 on 2022-11-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserve',
            options={'ordering': ['created'], 'verbose_name': 'Reserva pontual', 'verbose_name_plural': 'Reservas pontuais'},
        ),
        migrations.RenameField(
            model_name='reserve',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='reserve',
            old_name='refresh_at',
            new_name='modified',
        ),
        migrations.AddField(
            model_name='reserve',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
