# Generated by Django 4.0.8 on 2023-02-11 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reserva", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReserveDay",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Data da reserva")),
                (
                    "shift",
                    models.CharField(
                        choices=[("M", "Manhã"), ("T", "Tarde"), ("N", "Noite")],
                        max_length=1,
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reserves",
                        to="reserva.classroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dia da reserva",
                "verbose_name_plural": "Dias da reserva",
                "ordering": ["date", "shift"],
            },
        ),
        migrations.DeleteModel(
            name="MaterialReservation",
        ),
        migrations.AlterModelOptions(
            name="reserve",
            options={
                "ordering": ["created"],
                "verbose_name": "Reserva pontual",
                "verbose_name_plural": "Reservas pontuais",
            },
        ),
        migrations.RenameField(
            model_name="reserve",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="reserve",
            old_name="refresh_at",
            new_name="modified",
        ),
        migrations.RenameField(
            model_name="periodreserve",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="periodreserve",
            old_name="refresh_at",
            new_name="modified",
        ),
        migrations.AddField(
            model_name="periodreserve",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reserve",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="periodreserve",
            name="class_period",
            field=models.CharField(max_length=8, verbose_name="Turma"),
        ),
        migrations.AlterField(
            model_name="periodreserve",
            name="classcode",
            field=models.CharField(max_length=16, verbose_name="Código do componente"),
        ),
        migrations.AlterField(
            model_name="periodreserve",
            name="classroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reserva.classroom",
                verbose_name="Sala de aula",
            ),
        ),
        migrations.AlterField(
            model_name="periodreserve",
            name="course",
            field=models.CharField(
                choices=[
                    ("ESU01", "Técnico em Enfermagem"),
                    ("ESU02", "Técnico em Registros e Informações em Saúde"),
                    ("ESU06", "Técnico em Vigilância em Saúde"),
                    ("ESU05", "Técnico em Agente Comunitário de Saúde"),
                    ("ESU07", "Técnico em Massoterapia"),
                    ("ESU10", "Graduação Tecnológica em Gestão Hospitalar"),
                    ("MPPSE", "Mestrado Profissional"),
                    ("ENF", "Outros"),
                ],
                max_length=8,
                verbose_name="Nome do curso",
            ),
        ),
        migrations.AlterField(
            model_name="periodreserve",
            name="period",
            field=models.CharField(max_length=8, verbose_name="Período letivo"),
        ),
        migrations.AlterField(
            model_name="periodreserve",
            name="shift",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("M", "Manhã"), ("T", "Tarde"), ("N", "Noite")],
                max_length=5,
                verbose_name="Turno",
            ),
        ),
        migrations.AlterField(
            model_name="periodreserve",
            name="status",
            field=models.CharField(
                choices=[
                    ("E", "Esperando"),
                    ("C", "Cancelada"),
                    ("R", "Rejeitada"),
                    ("A", "Aprovada"),
                    ("D", "Concluída"),
                ],
                default="E",
                max_length=1,
                verbose_name="Estado da reserva",
            ),
        ),
        migrations.AlterField(
            model_name="periodreserve",
            name="weekdays",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("1", "Segunda-feira"),
                    ("2", "Terça-feira"),
                    ("3", "Quarta-feira"),
                    ("4", "Quinta-feira"),
                    ("5", "Sexta-feira"),
                    ("6", "Sábado"),
                    ("7", "Domingo"),
                ],
                max_length=13,
                verbose_name="Dias da semana",
            ),
        ),
        migrations.AlterField(
            model_name="reserve",
            name="classroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reserva.classroom",
                verbose_name="Sala de aula",
            ),
        ),
        migrations.AlterField(
            model_name="reserve",
            name="event",
            field=models.CharField(max_length=100, verbose_name="Evento"),
        ),
        migrations.AlterField(
            model_name="reserve",
            name="shift",
            field=models.CharField(
                choices=[("M", "Manhã"), ("T", "Tarde"), ("N", "Noite")],
                max_length=1,
                verbose_name="Turno",
            ),
        ),
        migrations.AlterField(
            model_name="reserve",
            name="status",
            field=models.CharField(
                choices=[
                    ("E", "Esperando"),
                    ("C", "Cancelada"),
                    ("R", "Rejeitada"),
                    ("A", "Aprovada"),
                    ("D", "Concluída"),
                ],
                default="E",
                max_length=1,
                verbose_name="Estado da reserva",
            ),
        ),
        migrations.AlterField(
            model_name="userclassroom",
            name="classroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responsible",
                to="reserva.classroom",
                verbose_name="Sala",
            ),
        ),
        migrations.AlterField(
            model_name="userclassroom",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classrooms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsável",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userclassroom",
            unique_together={("user", "classroom")},
        ),
        migrations.DeleteModel(
            name="PeriodReserveDay",
        ),
        migrations.AddField(
            model_name="reserveday",
            name="period",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="reserva.periodreserve",
            ),
        ),
        migrations.AddField(
            model_name="reserveday",
            name="reserve",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="reserva.reserve",
            ),
        ),
    ]
