# Generated by Django 4.0.8 on 2023-02-11 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_reserveday_delete_materialreservation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PeriodReserve',
            new_name='Period',
        ),
    ]
