# Generated by Django 3.2.8 on 2023-12-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_alter_period_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='course',
            field=models.CharField(choices=[('ESU01', 'Técnico em Enfermagem'), ('ESU02', 'Técnico em Registros e Informações em Saúde'), ('ESU06', 'Técnico em Vigilância em Saúde'), ('ESU05', 'Técnico em Agente Comunitário de Saúde'), ('ESU07', 'Técnico em Massoterapia'), ('ESU10', 'Graduação Tecnológica em Gestão Hospitalar'), ('MPPSE', 'Mestrado Profissional'), ('ESU08', 'Técnico em Cuidados de Idosos'), ('ENF', 'Outros')], max_length=8, verbose_name='Nome do curso'),
        ),
    ]
