# Generated by Django 4.0.8 on 2022-11-23 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reserva', '0003_alter_reserve_created_alter_reserve_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclassroom',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to='reserva.classroom', verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='userclassroom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
    ]
