# Generated by Django 4.0.9 on 2023-02-14 04:47

from django.db import migrations, models
import uuid


def forwards(apps, schema_editor):
    reserve_model_cls = apps.get_models("reserva", "Reserve")
    queryset = reserve_model_cls.objects.all()
    for reserve in queryset:
        reserve.uuid = uuid.uuid4()
        reserve.save()


class Migration(migrations.Migration):
    dependencies = [
        ("reserva", "0004_alter_period_created_alter_period_modified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserve",
            name="uuid",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(forwards),
        migrations.AlterField(
            model_name="reserve",
            name="uuid",
            field=models.CharField(
                blank=True, max_length=100, unique=True, default=uuid.uuid4
            ),
        ),
    ]
