# Generated by Django 4.2.11 on 2026-03-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_alter_period_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='justification_required',
            field=models.BooleanField(default=False, verbose_name='Requer objetivo/observações para uso'),
        ),
    ]
