# Generated by Django 4.0.9 on 2023-02-14 04:41

from django.db import migrations, models
import uuid

def forwards(apps, schema_editor):
    reserve_model_cls = apps.get_model("reserva", "Reserve")
    queryset = reserve_model_cls.objects.all()
    for reserve in queryset:
        reserve.uuid = uuid.uuid4()
class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_alter_period_created_alter_period_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.RunPython(forwards)
    ]
