# Generated by Django 4.0.8 on 2022-11-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_alter_userclassroom_classroom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodreserve',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='periodreserve',
            old_name='refresh_at',
            new_name='modified',
        ),
    ]
