# Generated by Django 4.0.9 on 2023-02-12 22:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_alter_period_created_alter_period_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='uuid',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
