# Generated by Django 4.0.9 on 2023-02-16 22:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_reserve_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='weekdays',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Segunda'), ('2', 'Terça'), ('3', 'Quarta'), ('4', 'Quinta'), ('5', 'Sexta'), ('6', 'Sábado'), ('7', 'Domingo')], max_length=13, verbose_name='Dias da semana'),
        ),
    ]
