# Generated by Django 4.0.9 on 2023-02-14 04:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_reserve_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='uuid',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
