# Generated by Django 4.0.9 on 2023-02-17 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_reserve_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='is_removed',
        ),
    ]
