# Generated by Django 4.0.9 on 2023-02-17 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0006_alter_period_weekdays'),
        ('reserva', '0006_remove_period_is_removed'),
    ]

    operations = [
    ]
