# Generated by Django 4.0.8 on 2022-12-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0006_periodreserve_is_removed_alter_periodreserve_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='shift',
            field=models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], max_length=1, verbose_name='Turno'),
        ),
    ]
