# Generated by Django 4.0.9 on 2023-03-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0007_merge_20230217_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Visível ao público'),
        ),
    ]
