# Generated by Django 4.0.9 on 2023-04-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0008_classroom_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capacidade'),
        ),
    ]
