# Generated by Django 4.0.8 on 2022-12-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0008_alter_reserve_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='status',
            field=models.CharField(choices=[('A', 'Aprovado'), ('R', 'Rejeitado'), ('E', 'Esperando'), ('C', 'Concluído')], default='E', max_length=1, verbose_name='Estado da reserva'),
        ),
    ]
