# Generated by Django 4.0.8 on 2023-02-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0009_alter_reserve_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='status',
            field=models.CharField(choices=[('E', 'Esperando'), ('C', 'Cancelado'), ('R', 'Rejeitado'), ('A', 'Aprovado'), ('D', 'Concluído')], default='E', max_length=1, verbose_name='Estado da reserva'),
        ),
    ]
