# Generated by Django 4.0.8 on 2023-02-05 04:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0010_alter_reserve_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('E', 'Esperando'), ('C', 'Cancelado'), ('R', 'Rejeitado'), ('A', 'Aprovado'), ('D', 'Concluído')], default='E', max_length=1, verbose_name='Estado da reserva')),
                ('date_begin', models.DateField(verbose_name='Início do período')),
                ('date_end', models.DateField(verbose_name='Fim do período')),
                ('workload', models.IntegerField(null=True, verbose_name='Carga horária')),
                ('weekdays', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=13, verbose_name='Dias da semana')),
                ('classname', models.CharField(max_length=100, verbose_name='Nome da turma')),
                ('classcode', models.CharField(max_length=16, verbose_name='Código do componente')),
                ('course', models.CharField(choices=[('ESU01', 'Técnico em Enfermagem'), ('ESU02', 'Técnico em Registros e Informações em Saúde'), ('ESU06', 'Técnico em Vigilância em Saúde'), ('ESU05', 'Técnico em Agente Comunitário de Saúde'), ('ESU07', 'Técnico em Massoterapia'), ('ESU10', 'Graduação Tecnológica em Gestão Hospitalar'), ('MPPSE', 'Mestrado Profissional'), ('ENF', 'Outros')], max_length=8, verbose_name='Nome do curso')),
                ('period', models.CharField(max_length=8, verbose_name='Período letivo')),
                ('class_period', models.CharField(max_length=8, verbose_name='Turma')),
                ('shift', multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], max_length=5, verbose_name='Turno')),
                ('requester', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=16, verbose_name='Telefone')),
                ('equipment', models.CharField(blank=True, help_text='Informe se preciso, algum equipamento ou software adicional necessário para as aulas.', max_length=200, null=True, verbose_name='Equipamento multimídia')),
                ('obs', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Observação')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.classroom', verbose_name='Sala de aula')),
            ],
            options={
                'verbose_name': 'Reserva de período',
                'verbose_name_plural': 'Reservas de período',
                'ordering': ['-period', '-class_period', 'course', 'date_begin', 'date_end', 'classname'],
            },
        ),
        migrations.CreateModel(
            name='ReserveDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data da reserva')),
                ('shift', models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], default='M', max_length=1, verbose_name='Turno')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='reserva.classroom', verbose_name='Sala de aula')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='reserva.period')),
            ],
            options={
                'verbose_name': 'Dia da reserva',
                'verbose_name_plural': 'Dias da reserva',
                'ordering': ['date', 'shift'],
            },
        ),
        migrations.DeleteModel(
            name='MaterialReservation',
        ),
        migrations.RemoveField(
            model_name='periodreserveday',
            name='period',
        ),
        migrations.AlterField(
            model_name='reserve',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.classroom', verbose_name='Sala de aula'),
        ),
        migrations.DeleteModel(
            name='PeriodReserve',
        ),
        migrations.DeleteModel(
            name='PeriodReserveDay',
        ),
        migrations.AddField(
            model_name='reserveday',
            name='reserve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='reserva.reserve'),
        ),
    ]
