# Generated by Django 4.0.8 on 2023-02-09 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reserva', '0011_period_reserveday_delete_materialreservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='weekdays',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Segunda-feira'), ('2', 'Terça-feira'), ('3', 'Quarta-feira'), ('4', 'Quinta-feira'), ('5', 'Sexta-feira'), ('6', 'Sábado'), ('7', 'Domingo')], max_length=13, verbose_name='Dias da semana'),
        ),
        migrations.AlterField(
            model_name='reserveday',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='reserva.classroom'),
        ),
        migrations.AlterField(
            model_name='reserveday',
            name='shift',
            field=models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='userclassroom',
            unique_together={('user', 'classroom')},
        ),
    ]
