# Generated by Django 4.0.8 on 2023-02-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0012_alter_period_weekdays_alter_reserveday_classroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='status',
            field=models.CharField(choices=[('E', 'Esperando'), ('C', 'Cancelada'), ('R', 'Rejeitada'), ('A', 'Aprovada'), ('D', 'Concluída')], default='E', max_length=1, verbose_name='Estado da reserva'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='status',
            field=models.CharField(choices=[('E', 'Esperando'), ('C', 'Cancelada'), ('R', 'Rejeitada'), ('A', 'Aprovada'), ('D', 'Concluída')], default='E', max_length=1, verbose_name='Estado da reserva'),
        ),
    ]
