# Generated by Django 4.1 on 2022-09-01 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('link', models.CharField(max_length=255, verbose_name='Link')),
                ('order', models.IntegerField(help_text='Ordem que aparecerá na barra de menu', verbose_name='Ordem')),
                ('decoration', models.CharField(blank=True, help_text='Classes CSS extra', max_length=100, null=True, verbose_name='Class estilo')),
            ],
            options={
                'verbose_name': 'Item do menu',
                'verbose_name_plural': 'Itens do menu',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DashboardSubItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('related_name', models.CharField(max_length=50, verbose_name='Nome relacionado')),
                ('link', models.CharField(max_length=255, verbose_name='Link')),
                ('order', models.IntegerField(verbose_name='Ordem')),
                ('decoration', models.CharField(blank=True, help_text='Classes CSS extra', max_length=100, null=True, verbose_name='Class estilo')),
                ('aditional', models.TextField(blank=True, max_length=512, null=True, verbose_name='HTML Adicional')),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboarditens')),
            ],
            options={
                'verbose_name': 'Subitem do menu',
                'verbose_name_plural': 'Subitens dos menus',
                'ordering': ['menu', 'order'],
            },
        ),
    ]
