# Generated by Django 4.2.11 on 2025-09-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='arquivo',
            field=models.FileField(default=1, upload_to='arquivos_registro/'),
            preserve_default=False,
        ),
    ]
