# Generated by Django 4.2.11 on 2025-09-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_pessoa_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='arquivo',
            field=models.FileField(upload_to='media/'),
        ),
    ]
