# Generated by Django 4.2.11 on 2025-09-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_alter_pessoa_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='arquivo',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
