# Generated by Django 4.2.11 on 2025-09-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_remove_pessoa_arquivo_pessoa_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='arquivo',
            field=models.FileField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
