# Generated by Django 4.2.11 on 2025-09-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_pessoa_arquivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ['numero']},
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='nome',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='descricao_item',
            field=models.TextField(blank=True, verbose_name='Descrição do item'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='documentos_comprobatorios',
            field=models.TextField(blank=True, verbose_name='Documentos comprobatórios'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='numero',
            field=models.PositiveIntegerField(default=1, verbose_name='Nº'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='pessoas',
            field=models.CharField(blank=True, max_length=255, verbose_name='Pessoas'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='pontuacao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Pontuação'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='saberes_competencias',
            field=models.CharField(default=1, max_length=255, verbose_name='Saberes e Competências'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='solicitar_documentacao_chefia',
            field=models.BooleanField(default=False, verbose_name='Solicitar documentação a chefia'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='unidade_medida',
            field=models.CharField(blank=True, max_length=50, verbose_name='Unidade de Medida'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='upload_declaracao',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Upload declaração'),
        ),
    ]
