# Generated by Django 4.2.11 on 2025-09-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_alter_pessoa_upload_declaracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='numero',
            field=models.PositiveIntegerField(unique=True, verbose_name='Nº'),
        ),
    ]
