# Generated by Django 4.2.11 on 2025-09-09 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_pessoa_created_at_pessoa_uid_pessoa_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='upload_declaracao',
        ),
        migrations.CreateModel(
            name='PessoaDeclaracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='arquivos_registro/', verbose_name='Declaração')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaracoes', to='registro.pessoa')),
            ],
        ),
    ]
