# Generated by Django 4.0.9 on 2023-09-18 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='Marca')),
                ('received_at', models.DateField(blank=True, null=True, verbose_name='Recebido em')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localização')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('qr_code', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.esimage')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
                'ordering': ['name', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Almoxarifado',
                'verbose_name_plural': 'Almoxarifados',
            },
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='laboratorio.material')),
                ('initial_quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantidade inicial')),
                ('measure_unit', models.CharField(blank=True, max_length=32, null=True, verbose_name='Unidade de armazenamento')),
                ('quantity', models.IntegerField(verbose_name='Quantidade disponível')),
                ('alert_below', models.IntegerField(verbose_name='Nível crítico')),
                ('expiration', models.DateField(blank=True, null=True, verbose_name='Data de validade')),
                ('sold_out_at', models.DateTimeField(blank=True, null=True, verbose_name='Esgotado em')),
            ],
            options={
                'verbose_name': 'Material de consumo',
                'verbose_name_plural': 'Materiais de consumo',
                'ordering': ['name', '-created'],
            },
            bases=('laboratorio.material',),
            managers=[
                ('available_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='laboratorio.warehouse'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('quantity', models.IntegerField(verbose_name='Quantidade atualizada')),
                ('prev_quantity', models.IntegerField(default=0, verbose_name='Quantidade anterior')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='laboratorio.material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de material',
                'verbose_name_plural': 'Histórico de materiais',
                'ordering': ['item__id', '-created'],
            },
        ),
        migrations.CreateModel(
            name='UserWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibles', to='laboratorio.warehouse')),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
                'unique_together': {('user', 'warehouse')},
            },
        ),
        migrations.CreateModel(
            name='Permanent',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='laboratorio.material')),
                ('number', models.CharField(max_length=255, unique=True, verbose_name='Tombamento')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponível'), ('UNAVAILABLE', 'Indisponível')], default='AVAILABLE', max_length=11, verbose_name='Status')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='laboratorio.category')),
            ],
            options={
                'verbose_name': 'Material permanente',
                'verbose_name_plural': 'Materiais permanentes',
                'ordering': ['name', '-created'],
            },
            bases=('laboratorio.material',),
        ),
    ]
