# Generated by Django 4.0.8 on 2023-01-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='prev_quantity',
            field=models.IntegerField(default=0, verbose_name='Quantidade anterior'),
        ),
        migrations.AlterField(
            model_name='history',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantidade atualizada'),
        ),
    ]
