# Generated by Django 4.0.8 on 2023-01-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_history_prev_quantity_alter_history_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
