# Generated by Django 4.0.9 on 2023-03-22 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_warehouse_alter_material_options_material_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['name', '-created'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materiais'},
        ),
    ]
