# Generated by Django 4.0.9 on 2025-02-04 18:41

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_add_materialti_consumableti'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumableti',
            options={'ordering': ['name', '-created'], 'verbose_name': 'Material de consumo (TI)', 'verbose_name_plural': 'Materiais de consumo (TI)'},
        ),
        migrations.AlterModelOptions(
            name='materialti',
            options={'ordering': ['name', '-created'], 'verbose_name': 'Material (TI)', 'verbose_name_plural': 'Materiais (TI)'},
        ),
        migrations.AlterModelManagers(
            name='consumableti',
            managers=[
                ('available_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='materialti',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='materialti',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialti',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='materialti',
            name='description',
            field=models.TextField(default=1, verbose_name='Descrição (TI)'),
            preserve_default=False,
        ),
    ]
