# Generated by Django 4.0.9 on 2023-04-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_alter_material_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumable',
            options={'ordering': ['name', '-created'], 'verbose_name': 'Material de consumo', 'verbose_name_plural': 'Materiais de consumo'},
        ),
        migrations.AlterModelOptions(
            name='permanent',
            options={'ordering': ['name', '-created'], 'verbose_name': 'Material permanente', 'verbose_name_plural': 'Materiais permanentes'},
        ),
    ]
