# Generated by Django 4.0.8 on 2023-01-12 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_material_is_removed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='material',
            old_name='qr',
            new_name='qr_code',
        ),
        migrations.RemoveField(
            model_name='material',
            name='alert_below',
        ),
        migrations.RemoveField(
            model_name='material',
            name='expiration',
        ),
        migrations.RemoveField(
            model_name='material',
            name='number',
        ),
        migrations.RemoveField(
            model_name='material',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='material',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='material',
            name='type',
        ),
        migrations.AddField(
            model_name='material',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='laboratorio.material')),
                ('expiration', models.DateField(blank=True, null=True, verbose_name='Data de validade')),
                ('alert_below', models.IntegerField(blank=True, null=True, verbose_name='Nível crítico')),
                ('reference', models.IntegerField(blank=True, null=True, verbose_name='Valor de referência')),
                ('quantity', models.IntegerField(verbose_name='Quantidade disponível')),
            ],
            options={
                'verbose_name': 'Material permanente',
                'verbose_name_plural': 'Materiais permanentes',
                'ordering': ['-created'],
            },
            bases=('laboratorio.material',),
        ),
        migrations.CreateModel(
            name='Permanent',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='laboratorio.material')),
                ('number', models.CharField(max_length=255, unique=True, verbose_name='Tombamento')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponível'), ('UNAVAILABLE', 'Indisponível')], default='AVAILABLE', max_length=11, verbose_name='Status')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratorio.category')),
            ],
            options={
                'verbose_name': 'Material permanente',
                'verbose_name_plural': 'Materiais permanentes',
                'ordering': ['-created'],
            },
            bases=('laboratorio.material',),
        ),
    ]
