# Generated by Django 4.0.9 on 2025-02-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_alter_consumableti_options_alter_materialti_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseti',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
