# Generated by Django 4.0.8 on 2023-01-13 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0004_category_rename_qr_material_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permanent',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='laboratorio.category'),
        ),
    ]
