# Generated by Django 4.0.8 on 2023-01-16 18:54

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0005_alter_permanent_category'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='consumable',
            managers=[
                ('available_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='consumable',
            name='sold_out_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Esgotado em'),
        ),
    ]
