# Generated by Django 4.2.11 on 2025-02-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0005_add_ti_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumableti',
            name='status',
            field=models.CharField(choices=[('Solicitado', 'Solicitado'), ('Não solicitado', 'Não solicitado')], default='Não solicitado', max_length=15),
        ),
        migrations.AlterField(
            model_name='consumableti',
            name='sold_out_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Solicitado em'),
        ),
    ]
