# Generated by Django 4.2.11 on 2025-02-06 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0006_consumableti_status_alter_consumableti_sold_out_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumableti',
            old_name='status',
            new_name='pedido',
        ),
    ]
