# Generated by Django 4.2.11 on 2025-02-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0007_rename_status_consumableti_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumableti',
            name='sold_out_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pedido em'),
        ),
    ]
