# Generated by Django 4.0.8 on 2023-02-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0007_alter_consumable_options_remove_consumable_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='measure_unit',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Unidade de armazenamento'),
        ),
    ]
