# Generated by Django 4.2.11 on 2025-02-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0008_alter_consumableti_sold_out_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumableti',
            name='sold_out_at',
            field=models.DateField(blank=True, null=True, verbose_name='Pedido em'),
        ),
    ]
