CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    "default": {
        "toolbar": [
            [
                "Undo",
                "Redo",
                "-",
                "Format",
                "-",
                "Bold",
                "Italic",
                "Underline",
                "Image",
                "HorizontalRule",
                "-",
                "Link",
                "Unlink",
                "-",
                "Cut",
                "Copy",
                "PasteText",
                "-",
                "Subscript",
                "Superscript",
                "SpecialChar",
                "-",
                "Outdent",
                "Indent",
                "-",
                "BulletedList",
                "NumberedList",
            ]
        ],
        "width": "100%",
        "height": 500,
        "toolbarCanCollapse": False,
        "entities_latin": False,
        "basicEntities": False,
    },
    "events": {
        "toolbar": [
            [
                "Undo",
                "Redo",
                "-",
                "Format",
                "-",
                "Bold",
                "Italic",
                "Underline",
                "Image",
                "HorizontalRule",
                "-",
                "Link",
                "Unlink",
                "-",
                "Cut",
                "Copy",
                "PasteText",
                "-",
                "Subscript",
                "Superscript",
                "SpecialChar",
                "-",
                "Outdent",
                "Indent",
                "-",
                "BulletedList",
                "NumberedList",
            ]
        ],
        "width": "100%",
        "height": 180,
        "toolbarCanCollapse": False,
        "entities_latin": False,
        "basicEntities": False,
    },
    "page": {
        "removePlugins": "stylesheetparser",
        "allowedContent": True,
        "toolbar": [
            [
                "Source",
                "Preview",
                "Undo",
                "Redo",
                "-",
                "Format",
                "Font",
                "FontSize",
                "-",
                "Bold",
                "Italic",
                "Underline",
                "Image",
                "HorizontalRule",
                "-",
                "JustifyLeft",
                "JustifyCenter",
                "JustifyRight",
                "JustifyBlock",
                "-",
                "Link",
                "Unlink",
                "-",
                "Cut",
                "Copy",
                "Paste",
                "PasteText",
                "-",
                "Subscript",
                "Superscript",
                "SpecialChar",
                "-",
                "Outdent",
                "Indent",
                "-",
                "BulletedList",
                "NumberedList",
                "-",
            ]
        ],
        "width": "100%",
        "height": 600,
        "toolbarCanCollapse": False,
        "extraPlugins": ",".join(["codesnippet", "codesnippetgeshi", "div"]),
        "codeSnippet_theme": "railscasts",
        "entities_latin": False,
        "basicEntities": False,
    },
}
