# Generated by Django 4.0.8 on 2022-12-22 18:29

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('expiration', models.DateField(blank=True, null=True, verbose_name='Data de validade')),
                ('type', models.CharField(choices=[('D', 'Durável'), ('C', 'Consumível')], max_length=1, verbose_name='Tipo')),
                ('quantity', models.IntegerField(verbose_name='Quantidade disponível')),
                ('received_date', models.DateField(verbose_name='Recebido em')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
                'ordering': ['-created'],
            },
        ),
    ]
