# Generated by Django 4.0.8 on 2023-01-03 02:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0002_material_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='alert_below',
            field=models.IntegerField(blank=True, null=True, verbose_name='Alerta'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('quantity', models.IntegerField(verbose_name='Quantidade disponível')),
                ('type', models.CharField(choices=[('R', 'Remoção'), ('A', 'Adição')], max_length=1, verbose_name='Tipo')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almoxarifado.material')),
            ],
            options={
                'verbose_name': 'Histórico de material',
                'verbose_name_plural': 'Histórico de materiais',
                'ordering': ['material__id', '-created'],
            },
        ),
    ]
