# Generated by Django 4.0.7 on 2022-10-25 23:33

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome do evento')),
                ('date_begin', models.DateField(verbose_name='Data de início')),
                ('date_end', models.DateField(verbose_name='Data de término')),
                ('local', models.CharField(default='A Definir', max_length=255, verbose_name='Local')),
                ('contact', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('coordination', models.CharField(max_length=255, verbose_name='Coordenação')),
                ('target', models.TextField(null=True, verbose_name='Público alvo')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.esimage', verbose_name='Imagem')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='eventos.event')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.file')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Informação')),
                ('details', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Detalhes')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='eventos.event')),
            ],
            options={
                'ordering': ['event__id', 'name'],
            },
        ),
    ]
